name: Publish

on:
  push:
    branches:
      - v1.1

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          8
          16
          17
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Get version from gradle.properties
      run: |
        VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get git hash
      run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew chiseledBuild -Pversion="${VERSION}+${GIT_HASH}"

    - uses: actions/upload-artifact@v4
      with:
        name: pv-addon-discs
        path: |
          plugin/build/libs/*.jar
          !plugin/build/libs/*-@(sources).jar
